import type { Projects } from "./types"

export const PROJECTS: Projects = [
	{
		company: "Vitti Logistics",
		images: ["/projects/vitti-vsta/cover.png"],
		liveUrl: "",
		githubUrl: "",
		technologies: [
			"Node.js",
			"Express",
			"React",
			"SQL Server",
			"Azure",
			"Docker",
			"Azure DevOps",
			"Microservices",
		],
		year: 2025,
		key: "vittiVsta",
	},
	{
		company: "Cobalto Inmuebles",
		images: ["/projects/cobalto-tenant/cover.png"],
		liveUrl: "https://cobalto.com.mx/",
		appleUrl: "https://apps.apple.com/mx/app/cobalto-inmuebles/id1472266028",
		androidUrl: "https://play.google.com/store/apps/details?id=com.aupa.cobalto&hl=es_MX",
		githubUrl: "",
		technologies: ["React Native", "TypeScript", "Figma", "Mobile Architecture"],
		year: 2024,
		key: "cobaltoTenant",
	},

	{
		company: "Cobalto Inmuebles",
		images: ["/projects/cobalto-security/cover.png"],
		liveUrl: "https://cobalto.com.mx/",
		androidUrl: "",
		technologies: ["React Native", "TypeScript", "QR Systems", "Mobile Development"],
		year: 2024,
		key: "cobaltoSecurity",
	},
	{
		company: "Forza Transportation Services",
		images: ["/projects/forza-drivers-app/cover.png"],
		liveUrl: "https://forzatrans.com/",
		androidUrl: "https://play.google.com/store/apps/details?id=com.driverappds",
		appleUrl: "https://apps.apple.com/mx/app/forza-drivers/id1611661768",
		technologies: ["React Native", "TypeScript", "Node.js", "Maps API"],
		year: 2024,
		key: "forzaDriversApp",
	},

	{
		company: "Forza Transportation Services",
		images: ["/projects/forza-fleet-gate/cover.png"],
		liveUrl: "https://forzatrans.com/",
		androidUrl: "https://play.google.com/store/apps/details?id=com.forzatrans.fleet.gate",
		technologies: ["React Native", "Node.js", "CTPAT Workflow"],
		year: 2024,
		key: "forzaFleetGate",
	},

	{
		company: "Forza Transportation Services",
		images: ["https://placehold.co/800x600"],
		liveUrl: "https://forzatrans.com/",
		technologies: ["React Native", "QR Systems", "Node.js"],
		year: 2024,
		key: "forzaAccessApp",
	},

	{
		company: "Forza Transportation Services",
		images: ["/projects/forza-tms/cover.png"],
		liveUrl: "https://forzatrans.com/",
		androidUrl: "https://play.google.com/store/apps/details?id=com.forzatrans.forza.core",
		githubUrl: "",
		technologies: ["React Native", "TypeScript", "Node.js"],
		year: 2024,
		key: "forzaTMSApp",
	},
	{
		company: "Forza Transportation Services",
		liveUrl: "",
		githubUrl: "",
		technologies: ["Node.js", "OpenAI API", "Baileys.js", "Automation"],
		year: 2024,
		key: "forzaWhatsAppChatbot",
	},

	{
		company: "Forza Transportation Services",
		liveUrl: "",
		githubUrl: "",
		technologies: ["Node.js", "Baileys.js", "Scoring Engine", "Automation"],
		year: 2024,
		key: "forzaDriverChatbot",
	},
	{
		company: "Gobierno del Estado de Nuevo León",
		images: ["/projects/genl-acceso/cover.png"],
		liveUrl: "https://acceso.nl.gob.mx/",
		technologies: ["React", "TypeScript", "AWS", "Node.js", "Laravel"],
		year: 2023,
		key: "genlAcceso",
	},
	{
		company: "Envia.com / Tendencys Innovation",
		images: ["/projects/envia/cover.png"],
		liveUrl: "https://envia.com/",
		technologies: ["Node.js", "FedEx API", "UPS API", "DHL API", "MySQL"],
		year: 2019,
		key: "enviaShippingEngine",
	},

	{
		company: "Envia.com / Tendencys Innovation",
		technologies: ["PHP", "Laravel", "MySQL", "REST API"],
		year: 2019,
		key: "enviaCodeIgniterToLaravel",
	},
	{
		company: "GTR Academy",
		liveUrl: "https://gtr.academy/",
		githubUrl: "https://github.com/raymundo-salazar/gtr-access-control",
		technologies: ["React Native", "Offline Storage", "QR Scanner", "Firebase"],
		year: 2023,
		key: "gtrQrApp",
	},

	{
		company: "GTR Academy",
		images: ["/projects/gtr-backoffice/cover.png"],
		liveUrl: "https://gtr.academy/",
		technologies: ["Vue.js", "Firebase Realtime", "Dashboard"],
		year: 2023,
		key: "gtrWebApp",
	},
	{
		company: "Globant",
		technologies: ["React Native", "TypeScript", "Animations", "UX"],
		year: 2022,
		key: "globantTecate",
	},

	{
		company: "Globant",
		images: ["/projects/globant-disney-plus/cover.png"],
		liveUrl: "https://www.disneyplus.com/",
		appleUrl: "https://apps.apple.com/es/app/disney/id1446075923",
		androidUrl: "https://play.google.com/store/apps/details?id=com.disney.disneyplus",
		technologies: ["React Native", "TypeScript", "UI/UX", "Animations"],
		year: 2022,
		key: "globantDisneyPlus",
	},
	{
		company: "VMC Technology / Media Falcon",
		images: ["/projects/ibugg/cover.png"],
		technologies: ["Hybrid Apps", "OCR", "JavaScript", "Mobile"],
		year: 2017,
		key: "ibugg",
	},

	{
		company: "VMC Technology / Media Falcon",
		technologies: ["Drag & Drop API", "JavaScript", "HTML", "CSS"],
		year: 2017,
		key: "vmcEmailEditor",
	},
	{
		company: "Positivo Agencia de Publicidad",
		images: ["/projects/llevaleflores/cover.png"],
		liveUrl: "https://llevaleflores.com/",
		technologies: ["PHP", "MySQL", "JavaScript", "HTML/CSS"],
		year: 2015,
		key: "llevaleflores",
	},
	{
		company: "Dilo con Flores",
		images: ["/projects/diloconflores/cover.png"],
		liveUrl: "https://diloconflores.com/",
		technologies: ["React", "Node.js", "MySQL", "Tailwind"],
		year: 2024,
		key: "diloconflores",
	},
]
