import { Users, Code, Palette, Smartphone } from "@lucide/astro"

export const EXPERIENCES = [
	{
		company: "Vitti Logistics",
		key: "vittiLeader",
		position: "Developer Leader",
		period: "2025",
		location: "Santa Catarina, NL",
		type: "leadership",
		icon: Users,
		color: "bg-emerald-500",
		technologies: [
			"Node.js",
			"Express",
			"Java",
			"React JS",
			"SQL Server",
			"Azure",
			"Docker",
			"Azure DevOps",
		],
	},
	{
		company: "Vitti Logistics",
		key: "vittiSupply",
		position: "Supply Chain Senior Developer",
		period: "2025",
		location: "Santa Catarina, NL",
		type: "engineering",
		icon: Code,
		color: "bg-indigo-500",
		technologies: [
			"Node.js",
			"Express",
			"Java",
			"React JS",
			"SQL Server",
			"Azure",
			"Docker",
			"Azure DevOps",
		],
	},
	{
		company: "Forza Transportation Services",
		key: "forzaLead",
		position: "Lead UI/UX & Mobile Developer",
		period: "2024 - 2025",
		location: "Remote",
		type: "leadership",
		icon: Users,
		color: "bg-blue-500",
		technologies: ["React Native", "TypeScript", "Node.js", "OpenAI API", "Baileys.js"],
	},
	{
		company: "Cobalto Inmuebles",
		key: "cobalto",
		position: "Mobile Developer & UI/UX Designer",
		period: "2024",
		location: "Remote",
		type: "development",
		icon: Smartphone,
		color: "bg-teal-500",
		technologies: ["React Native", "UI/UX Design", "Figma", "Mobile Development"],
	},
	{
		company: "Forza Transportation Services",
		key: "forzaSenior",
		position: "Senior Mobile Developer",
		period: "2023 - 2024",
		location: "Remote",
		type: "development",
		icon: Smartphone,
		color: "bg-purple-500",
		technologies: ["React Native", "Node.js", "WhatsApp API", "Baileys.js", "CI/CD"],
	},
	{
		company: "Gobierno del Estado de Nuevo León",
		key: "gobnlLead",
		position: "Lead Web UI Developer",
		period: "2021 - 2023",
		location: "Monterrey, NL",
		type: "leadership",
		icon: Users,
		color: "bg-green-500",
		technologies: ["React JS", "TypeScript", "AWS", "PHP Laravel", "Government Systems"],
	},
	{
		company: "Globant",
		key: "globant",
		position: "Mobile Developer",
		period: "2021 - 2022",
		location: "Remote",
		type: "development",
		icon: Smartphone,
		color: "bg-cyan-500",
		technologies: ["React Native", "TypeScript", "Mobile Development", "Team Collaboration"],
	},
	{
		company: "Gobierno del Estado de Nuevo León",
		key: "gobnlSenior",
		position: "Web UI Developer Senior",
		period: "2020 - 2021",
		location: "Monterrey, NL",
		type: "development",
		icon: Code,
		color: "bg-indigo-500",
		technologies: ["Node.js", "TypeScript", "React", "AWS", "PHP Laravel"],
	},
	{
		company: "Envia.com / Tendencys Innovation",
		key: "enviaLeader",
		position: "Front End Leader",
		period: "2019 - 2020",
		location: "Remote",
		type: "leadership",
		icon: Users,
		color: "bg-orange-500",
		technologies: ["React", "TypeScript", "Node.js", "CI/CD", "Team Leadership"],
	},
	{
		company: "Envia.com / Tendencys Innovation",
		key: "enviaSenior",
		position: "Web Developer Senior",
		period: "2018 - 2019",
		location: "Remote",
		type: "development",
		icon: Code,
		color: "bg-red-500",
		technologies: ["Node.js", "FedEx API", "UPS API", "DHL API", "PHP Laravel"],
	},
	{
		company: "GTR Academy",
		key: "gtr",
		position: "Fullstack Developer",
		period: "2023 - 2025",
		location: "Remote",
		type: "development",
		icon: Code,
		color: "bg-violet-500",
		technologies: [
			"Vue.js",
			"Firebase Auth",
			"Cloud Functions",
			"Cloud Firestore",
			"Firebase Storage",
			"React Native",
			"Geolocation",
			"QR Scanner",
		],
	},
	{
		company: "VMC Technology / Media Falcon",
		key: "vmc",
		position: "Web Developer / Graphic Designer",
		period: "2016 - 2018",
		location: "Monterrey, NL",
		type: "development",
		icon: Palette,
		color: "bg-pink-500",
		technologies: [
			"Hybrid Apps",
			"Drag & Drop API",
			"Email Templates",
			"Photoshop",
			"Illustrator",
		],
	},
	{
		company: "Positivo Agencia de Publicidad",
		key: "positivo",
		position: "Web Developer / Graphic Designer",
		period: "2013 - 2016",
		location: "Monterrey, NL",
		type: "development",
		icon: Palette,
		color: "bg-teal-500",
		technologies: ["PHP", "MySQL", "HTML/CSS", "JavaScript", "Photoshop", "Illustrator"],
	},
]
