import { Users, Code, Palette, Smartphone } from "@lucide/astro"

export const EXPERIENCES = [
	{
		id: 1,
		company: "Vitti Logistics",
		position: "Supply Chain Developer Senior",
		period: "2025",
		location: "Remote",
		type: "Leadership",
		icon: Users,
		color: "bg-emerald-500",
		description:
			"Tech Lead en desarrollo fullstack para sistemas de logística de transporte, exportación e importación. Liderazgo de equipo de desarrollo con enfoque en infraestructura cloud y automatización de despliegues.",
		achievements: [
			"Liderazgo técnico de equipo de desarrollo",
			"Diseño de infraestructura para aplicaciones web",
			"Implementación de despliegues automatizados con Azure DevOps",
			"Desarrollo de sistemas de logística, aduanas y facturación",
		],
		technologies: [
			"Node.js",
			"Express",
			"Java",
			"React JS",
			"SQL Server",
			"Azure",
			"Docker",
			"Azure DevOps",
		],
	},
	{
		id: 2,
		company: "Cobalto Inmuebles",
		position: "Mobile Developer & UI/UX Designer",
		period: "2024",
		location: "Remote",
		type: "Development",
		icon: Smartphone,
		color: "bg-teal-500",
		description:
			"Desarrollo completo de aplicaciones móviles para residentes y elementos de seguridad. Responsable tanto del diseño UX/UI como del desarrollo con React Native.",
		achievements: [
			"Diseño UX/UI completo de las aplicaciones",
			"Desarrollo de app móvil para residentes",
			"Desarrollo de app móvil para elementos de seguridad",
			"Lanzamiento exitoso de 2 aplicaciones en producción",
		],
		technologies: ["React Native", "UI/UX Design", "Figma", "Mobile Development"],
	},
	{
		id: 3,
		company: "Forza Transportation Services",
		position: "Lead UI/UX & Mobile Developer",
		period: "2024 - 2025",
		location: "Remote",
		type: "Leadership",
		icon: Users,
		color: "bg-blue-500",
		description:
			"Lideré equipos de desarrollo móvil y UI/UX, supervisando la creación de 4 aplicaciones móviles en producción. Implementé estándares de código, pipelines CI/CD y sistemas de diseño cohesivos.",
		achievements: [
			"Lanzamiento de 4 aplicaciones móviles en producción",
			"Integración de chatbot WhatsApp con OpenAI Assistant",
			"Establecimiento de mejores prácticas CI/CD",
			"Coordinación de equipos cross-funcionales",
		],
		technologies: ["React Native", "TypeScript", "Node.js", "OpenAI API", "Baileys.js"],
	},
	{
		id: 4,
		company: "Forza Transportation Services",
		position: "Senior Mobile Developer",
		period: "2023 - 2024",
		location: "Remote",
		type: "Development",
		icon: Smartphone,
		color: "bg-purple-500",
		description:
			"Desarrollo de aplicaciones React Native enfocadas en optimización de rendimiento y escalabilidad. Creación de chatbot automatizado para filtrado de candidatos conductores.",
		achievements: [
			"Optimización de performance en aplicaciones móviles",
			"Desarrollo de chatbot WhatsApp con Baileys.js",
			"Implementación de integración continua",
			"Filtrado automatizado de candidatos",
		],
		technologies: ["React Native", "Node.js", "WhatsApp API", "Baileys.js", "CI/CD"],
	},
	{
		id: 5,
		company: "Gobierno del Estado de Nuevo León",
		position: "Lead Web UI Developer",
		period: "2021 - 2023",
		location: "Monterrey, NL",
		type: "Leadership",
		icon: Users,
		color: "bg-green-500",
		description:
			"Lideré el equipo frontend en el desarrollo de sistemas administrativos y públicos para pagos de impuestos. Supervisé la transformación digital y definí estándares de desarrollo.",
		achievements: [
			"Transformación digital de sistemas gubernamentales",
			"Integración de TypeScript y AWS",
			"Implementación de deployment continuo",
			"Iniciativa de aplicación móvil gubernamental",
		],
		technologies: ["React JS", "TypeScript", "AWS", "PHP Laravel", "Government Systems"],
	},
	{
		id: 6,
		company: "Globant",
		position: "Mobile Developer",
		period: "2021 - 2022",
		location: "Remote",
		type: "Development",
		icon: Smartphone,
		color: "bg-cyan-500",
		description:
			"Desarrollo de aplicaciones móviles React Native para marcas reconocidas como Tecate, Coca Cola y Disney+. Participé en equipos de desarrollo trabajando en componentes específicos y pantallas de las aplicaciones.",
		achievements: [
			"Desarrollo de apps para Tecate, Coca Cola y Disney+",
			"Implementación de componentes y screens específicos",
			"Colaboración en equipos de desarrollo multidisciplinarios",
			"Optimización de experiencia de usuario móvil",
		],
		technologies: ["React Native", "TypeScript", "Mobile Development", "Team Collaboration"],
	},
	{
		id: 7,
		company: "Gobierno del Estado de Nuevo León",
		position: "Web UI Developer Senior",
		period: "2020 - 2021",
		location: "Monterrey, NL",
		type: "Development",
		icon: Code,
		color: "bg-indigo-500",
		description:
			"Migración de servicios PHP a Node.js para mejorar mantenimiento y estabilidad. Desarrollo de funcionalidades backend para gestión de transacciones electrónicas.",
		achievements: [
			"Migración exitosa PHP a Node.js",
			"Mejora de estabilidad de servicios",
			"Mantenimiento de aplicaciones TypeScript/React",
			"Desarrollo de features backend con Laravel",
		],
		technologies: ["Node.js", "TypeScript", "React", "AWS", "PHP Laravel"],
	},
	{
		id: 8,
		company: "Envia.com / Tendencys Innovation",
		position: "Front End Leader",
		period: "2019 - 2020",
		location: "Remote",
		type: "Leadership",
		icon: Users,
		color: "bg-orange-500",
		description:
			"Lideré el equipo de desarrollo frontend, manteniendo servicio Node.js de integración con múltiples transportistas. Implementé nuevas funcionalidades y optimicé la plataforma.",
		achievements: [
			"Liderazgo de equipo frontend",
			"Optimización de plataforma con React/TypeScript",
			"Definición de estándares de código",
			"Diseño de pipelines de integración continua",
		],
		technologies: ["React", "TypeScript", "Node.js", "CI/CD", "Team Leadership"],
	},
	{
		id: 9,
		company: "Envia.com / Tendencys Innovation",
		position: "Web Developer Senior",
		period: "2018 - 2019",
		location: "Remote",
		type: "Development",
		icon: Code,
		color: "bg-red-500",
		description:
			"Desarrollo de servicio Node.js para conexión con múltiples transportistas (FedEx, UPS, DHL). Migración de aplicaciones PHP CodeIgniter a Laravel.",
		achievements: [
			"Servicio multi-carrier en tiempo real",
			"Cálculos asíncronos de costos de envío",
			"Migración PHP CodeIgniter a Laravel",
			"Optimización de estructura de código",
		],
		technologies: ["Node.js", "FedEx API", "UPS API", "DHL API", "PHP Laravel"],
	},
	{
		id: 10,
		company: "GTR Academy",
		position: "Fullstack Developer",
		period: "2023 - 2025",
		location: "Remote",
		type: "Development",
		icon: Code,
		color: "bg-violet-500",
		description:
			"Desarrollo fullstack con Vue.js en frontend y servicios de Firebase en backend. Creación de sistema de ticketería digital con geolocalización, aplicación web espejo y app para escaneo QR offline.",
		achievements: [
			"Desarrollo frontend con Vue.js",
			"Integración de Firebase Authentication",
			"Sistema de ticketería digital con geolocalización",
			"Aplicación web espejo de la plataforma",
			"App para escaneo QR con funcionalidad offline",
			"Lanzamiento de 2 aplicaciones móviles en producción",
		],
		technologies: [
			"Vue.js",
			"Firebase Auth",
			"Cloud Functions",
			"Cloud Firestore",
			"Firebase Storage",
			"React Native",
			"Geolocation",
			"QR Scanner",
		],
	},
	{
		id: 11,
		company: "VMC Technology / Media Falcon",
		position: "Web Developer / Graphic Designer",
		period: "2016 - 2018",
		location: "Monterrey, NL",
		type: "Development",
		icon: Palette,
		color: "bg-pink-500",
		description:
			"Desarrollo de aplicaciones híbridas para múltiples plataformas. Creación de editor drag & drop para email marketing y diseño gráfico para campañas digitales.",
		achievements: [
			"Apps híbridas Android, iOS, Windows Phone",
			"Editor drag & drop para email marketing",
			"Diseño gráfico para redes sociales",
			"Mejora de presencia digital de marcas",
			"Lanzamiento de 1 aplicación móvil en producción",
		],
		technologies: [
			"Hybrid Apps",
			"Drag & Drop API",
			"Email Templates",
			"Photoshop",
			"Illustrator",
		],
	},
	{
		id: 12,
		company: "Positivo Agencia de Publicidad",
		position: "Web Developer / Graphic Designer",
		period: "2013 - 2016",
		location: "Monterrey, NL",
		type: "Development",
		icon: Palette,
		color: "bg-teal-500",
		description:
			"Desarrollo de sitios web personalizados e implementación de sistemas CRM para e-commerce. Diseño gráfico integral incluyendo branding y material publicitario.",
		achievements: [
			"Sitios web personalizados desde cero",
			"Sistemas CRM para e-commerce",
			"Creación de logotipos y branding",
			"Material visual para campañas publicitarias",
		],
		technologies: ["PHP", "MySQL", "HTML/CSS", "JavaScript", "Photoshop", "Illustrator"],
	},
]
