import type { WizardConfig } from "./types"

export const briefWizardConfig: WizardConfig = {
	eyebrow: "Brief para prospectos",
	title: "Cuentame que necesitas y armamos el brief correcto",
	subtitle: "Formulario guia para entender el proyecto",
	description:
		"Este wizard esta pensado para capturar contexto comercial, necesidad real y prioridades del proyecto sin perder claridad ni orden.",
	progressLabel: "Avance del brief",
	buttons: {
		previous: "Regresar",
		next: "Continuar",
		finish: "Enviar respuestas",
	},
	theme: {
		root: "min-h-screen w-full overflow-hidden bg-[radial-gradient(circle_at_top,_rgba(59,130,246,0.16),_transparent_35%),linear-gradient(135deg,_#09090b_0%,_#111827_48%,_#09090b_100%)] text-white",
		panel: "mx-auto flex min-h-screen w-full max-w-7xl flex-col justify-center px-4 py-8 sm:px-6 lg:px-8",
	},
	slides: [
		{
			id: "welcome",
			subtitle: "01. CONOZCAMOS TU PROYECTO",
			title: "Queremos entender lo que tienes en mente",
			questions: [
				{
					id: "welcomeCopy",
					type: "static",
					content: `
						<p><strong>Gracias por permitirnos conocer un poco mas sobre tu proyecto.</strong></p>
						<p>Ahora queremos entender <strong>como lo imaginas, que quieres lograr y que es importante para ti</strong>. Tus respuestas nos ayudaran a conocer mejor tu negocio y a definir una propuesta que tenga sentido para tus objetivos.</p>
						<p>No buscamos respuestas perfectas ni que tengas todo resuelto. <strong>Queremos conocer tus ideas, necesidades y prioridades</strong>, incluso aquellas que todavia estes explorando.</p>
						<p>A partir de aqui, te iremos guiando con algunas preguntas sencillas.</p>
					`,
				},
			],
		},
		{
			id: "contact",
			title: "Datos de contacto y empresa",
			subtitle: "Contacto",
			description:
				"Primero recolectamos la informacion basica del negocio y de quien responde.",
			questions: [
				{
					id: "contact_company_name",
					type: "text",
					label: "Nombre de la empresa o marca",
					required: true,
					placeholder: "Dilo con Flores",
				},
				{
					id: "contact_respondent_name",
					type: "text",
					label: "Nombre de quien responde",
					required: true,
					placeholder: "Raymundo Salazar",
				},
				{
					id: "contact_role",
					type: "radio",
					label: "Cual es tu rol dentro de la empresa?",
					required: true,
					options: [
						{ label: "Dueno / socio", value: "owner" },
						{ label: "Director / gerente general", value: "director" },
						{ label: "Marketing / crecimiento", value: "marketing" },
						{ label: "Ventas / comercial", value: "sales" },
						{ label: "Operaciones", value: "operations" },
						{ label: "Producto / tecnologia", value: "product" },
						{ label: "Otro", value: "other" },
					],
				},
				{
					id: "contact_email",
					type: "email",
					label: "Correo de contacto",
					required: true,
					placeholder: "raymundo@empresa.com",
				},
				{
					id: "contact_phone",
					type: "tel",
					label: "Telefono o WhatsApp",
					required: false,
					placeholder: "+52 81 8000 0000",
				},
				{
					id: "contact_website",
					type: "url",
					label: "Sitio web actual",
					description: "Si no tienen sitio, pueden dejarlo vacio.",
					required: false,
					placeholder: "https://...",
				},
				{
					id: "contact_social_links",
					type: "textarea",
					label: "Redes sociales o ligas importantes",
					required: false,
					rows: 4,
					placeholder: "Instagram, Facebook, LinkedIn, YouTube, etc.",
				},
			],
		},
		{
			id: "business_context",
			title: "Contexto general del negocio",
			subtitle: "Negocio",
			description: "Aqui buscamos entender que hace la empresa y como quiere ser percibida.",
			questions: [
				{
					id: "business_context_description",
					type: "text",
					label: "En una frase, que hace la empresa?",
					required: true,
					placeholder: "Creamos experiencias florales para eventos y clientes premium.",
				},
				{
					id: "business_context_category",
					type: "radio",
					label: "En que categoria encaja mejor la empresa?",
					required: true,
					options: [
						{ label: "Servicios profesionales", value: "services" },
						{ label: "Ecommerce / tienda en linea", value: "ecommerce" },
						{ label: "Retail / negocio local", value: "retail" },
						{ label: "Salud / bienestar", value: "health" },
						{ label: "Finanzas / seguros", value: "finance" },
						{ label: "Bienes raices / construccion", value: "real_estate" },
						{ label: "Educacion / cursos", value: "education" },
						{ label: "Eventos / experiencias", value: "events" },
						{ label: "Software / SaaS", value: "saas" },
						{ label: "Asociacion / fundacion", value: "nonprofit" },
						{ label: "Otro", value: "other" },
					],
				},
				{
					id: "business_context_stage",
					type: "radio",
					label: "En que etapa esta la empresa?",
					required: true,
					options: [
						{ label: "Idea / validacion inicial", value: "idea" },
						{ label: "Operando, pero todavia en etapa temprana", value: "early" },
						{ label: "Creciendo y buscando ordenar sistemas", value: "growing" },
						{ label: "Establecida, busca optimizar o escalar", value: "established" },
						{ label: "Reposicionamiento o cambio importante", value: "repositioning" },
						{ label: "No lo tengo claro", value: "not_sure" },
					],
				},
				{
					id: "business_context_purpose",
					type: "textarea",
					label: "Por que existe la empresa o marca?",
					description: "Cuentanos la motivacion, historia o razon principal.",
					required: true,
					rows: 4,
				},
				{
					id: "business_context_desired_perception",
					type: "textarea",
					label: "Que quieres que las personas entiendan, sientan o recuerden de la marca?",
					required: true,
					rows: 4,
				},
			],
		},
		{
			id: "project_goal",
			title: "Objetivo y problema principal",
			subtitle: "Meta",
			description: "Definimos que quiere lograr el proyecto y por que es importante ahora.",
			questions: [
				{
					id: "project_goal_primary_goal",
					type: "radio",
					label: "Cual es el objetivo principal del proyecto?",
					required: true,
					options: [
						{ label: "Generar mas prospectos", value: "more_leads" },
						{ label: "Generar mejores prospectos", value: "better_leads" },
						{ label: "Generar mas confianza", value: "trust" },
						{ label: "Mejorar conversion", value: "conversion" },
						{ label: "Mejorar posicionamiento de marca", value: "positioning" },
						{ label: "Aclarar oferta o mensaje", value: "clarity" },
						{ label: "Mejorar proceso comercial u operativo", value: "operations" },
						{ label: "Lanzar una nueva marca, servicio o producto", value: "launch" },
						{ label: "Redisenar o modernizar presencia digital", value: "redesign" },
						{ label: "No estoy seguro todavia", value: "not_sure" },
					],
				},
				{
					id: "project_goal_problem",
					type: "textarea",
					label: "Que problema especifico quieren resolver primero?",
					required: true,
					rows: 4,
				},
				{
					id: "project_goal_urgency_reason",
					type: "radio",
					label: "Por que es importante resolverlo ahora?",
					required: true,
					options: [
						{ label: "Estamos perdiendo oportunidades", value: "losing_sales" },
						{ label: "El crecimiento esta atorado", value: "growth_blocked" },
						{
							label: "La presencia actual ya no representa a la empresa",
							value: "outdated_presence",
						},
						{
							label: "Hay un lanzamiento o fecha importante",
							value: "launch_deadline",
						},
						{ label: "La competencia esta mejor posicionada", value: "competition" },
						{
							label: "El proceso interno es ineficiente",
							value: "internal_efficiency",
						},
						{ label: "Afecta confianza o reputacion", value: "reputation" },
						{
							label: "Queremos anticiparnos antes de que sea urgente",
							value: "proactive",
						},
						{ label: "No lo tengo claro", value: "not_sure" },
					],
				},
				{
					id: "project_goal_success_definition",
					type: "textarea",
					label: "Como sabrian que el proyecto fue exitoso?",
					required: true,
					rows: 4,
				},
				{
					id: "project_goal_priority",
					type: "radio",
					label: "Si tuvieran que elegir una sola prioridad, cual seria?",
					required: true,
					options: [
						{ label: "Que mas personas nos encuentren", value: "visibility" },
						{ label: "Que la marca genere mas confianza", value: "trust" },
						{ label: "Que mas visitantes contacten o compren", value: "conversion" },
						{ label: "Que la oferta se entienda mejor", value: "clarity" },
						{ label: "Que el proceso comercial sea mas claro", value: "sales_process" },
						{ label: "Poder medir resultados", value: "measurement" },
						{ label: "Lanzar rapido una primera version", value: "speed" },
						{ label: "Construir algo solido y escalable", value: "quality" },
					],
				},
			],
		},
		{
			id: "ideal_customer",
			title: "Cliente ideal",
			subtitle: "Audiencia",
			description:
				"Entendemos a quien quieren atraer y que problema vive antes de llegar con ustedes.",
			questions: [
				{
					id: "ideal_customer_description",
					type: "textarea",
					label: "Quien es su cliente ideal?",
					required: true,
					rows: 4,
				},
				{
					id: "ideal_customer_segment",
					type: "multiselect",
					label: "Que tipo de cliente quieren atraer principalmente?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Personas", value: "individuals" },
						{ label: "Familias", value: "families" },
						{ label: "Empresas", value: "businesses" },
						{ label: "Dueno / fundador / emprendedor", value: "founders" },
						{ label: "Directivos / profesionistas", value: "executives" },
						{ label: "Clientes locales", value: "local" },
						{ label: "Clientes nacionales", value: "national" },
						{ label: "Clientes premium", value: "premium" },
						{ label: "Clientes recurrentes", value: "recurring" },
						{ label: "No lo tenemos definido", value: "not_sure" },
					],
				},
				{
					id: "ideal_customer_trigger",
					type: "textarea",
					label: "Que necesidad, problema o situacion suele tener antes de buscarles?",
					required: true,
					rows: 4,
				},
				{
					id: "ideal_customer_objections",
					type: "multiselect",
					label: "Que dudas, miedos u objeciones tiene antes de comprar, contratar o contactarlos?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Precio", value: "price" },
						{ label: "Confianza", value: "trust" },
						{ label: "No sabe si lo necesita ahora", value: "urgency" },
						{ label: "Lo percibe complejo", value: "complexity" },
						{ label: "Esta comparando opciones", value: "comparison" },
						{
							label: "Tuvo una mala experiencia previa",
							value: "previous_bad_experience",
						},
						{ label: "Le preocupa tomar una mala decision", value: "decision_risk" },
						{ label: "No tiene tiempo para revisar", value: "time" },
						{ label: "No lo sabemos", value: "not_sure" },
						{ label: "Otro", value: "other" },
					],
				},
				{
					id: "ideal_customer_bad_fit",
					type: "textarea",
					label: "Que tipo de cliente no quieren atraer?",
					required: false,
					rows: 4,
				},
			],
		},
		{
			id: "offer",
			title: "Oferta y diferenciacion",
			subtitle: "Propuesta",
			description: "Aterrizamos que venden, por que les compran y que los hace distintos.",
			questions: [
				{
					id: "offer_main_offers",
					type: "textarea",
					label: "Cuales son sus productos, servicios o soluciones principales?",
					required: true,
					rows: 4,
				},
				{
					id: "offer_priority_offer",
					type: "text",
					label: "Cual producto, servicio o solucion quieren impulsar primero?",
					required: true,
					placeholder: "Servicio premium de diseno floral",
				},
				{
					id: "offer_differentiators",
					type: "textarea",
					label: "Que los hace diferentes de otras opciones en el mercado?",
					required: true,
					rows: 4,
				},
				{
					id: "offer_trust_proofs",
					type: "multiselect",
					label: "Que pruebas de confianza existen?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Testimonios", value: "testimonials" },
						{ label: "Casos de exito", value: "cases" },
						{ label: "Portafolio / trabajos anteriores", value: "portfolio" },
						{ label: "Certificaciones", value: "certifications" },
						{ label: "Anos de experiencia", value: "years_experience" },
						{ label: "Prensa / menciones", value: "media" },
						{ label: "Alianzas", value: "partners" },
						{ label: "Garantias", value: "guarantees" },
						{ label: "Resenas", value: "reviews" },
						{ label: "Resultados medibles", value: "data_results" },
						{ label: "Todavia no tenemos", value: "none" },
					],
				},
			],
		},
		{
			id: "sales_process",
			title: "Proceso comercial",
			subtitle: "Ventas",
			description: "Vemos como llegan hoy los prospectos y en donde se pierde valor.",
			questions: [
				{
					id: "sales_current_sources",
					type: "multiselect",
					label: "Como llegan hoy los prospectos o clientes?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Recomendaciones", value: "referrals" },
						{ label: "Google / busqueda organica", value: "google" },
						{ label: "Anuncios pagados", value: "paid_ads" },
						{ label: "Instagram", value: "instagram" },
						{ label: "Facebook", value: "facebook" },
						{ label: "TikTok", value: "tiktok" },
						{ label: "LinkedIn", value: "linkedin" },
						{ label: "WhatsApp", value: "whatsapp" },
						{ label: "Marketplaces / directorios", value: "marketplace" },
						{ label: "Eventos / networking", value: "events" },
						{ label: "Prospeccion directa", value: "outbound" },
						{ label: "Visita fisica", value: "walk_in" },
						{ label: "No lo sabemos", value: "not_sure" },
					],
				},
				{
					id: "sales_flow",
					type: "textarea",
					label: "Que pasa desde que alguien los contacta hasta que compra, agenda o contrata?",
					required: true,
					rows: 5,
				},
				{
					id: "sales_friction",
					type: "multiselect",
					label: "En que parte del proceso sienten que se pierden mas oportunidades?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "No llega suficiente gente", value: "traffic" },
						{ label: "Llegan prospectos poco calificados", value: "quality" },
						{ label: "No logramos generar suficiente confianza", value: "trust" },
						{ label: "Tardamos en responder", value: "response_time" },
						{ label: "Falta seguimiento", value: "follow_up" },
						{ label: "Se caen por precio", value: "pricing" },
						{ label: "La propuesta no convence", value: "proposal" },
						{ label: "El prospecto tarda mucho en decidir", value: "decision" },
						{ label: "No sabemos donde se pierden", value: "measurement" },
						{ label: "No lo tenemos claro", value: "not_sure" },
					],
				},
				{
					id: "sales_tools",
					type: "multiselect",
					label: "Que herramientas usan hoy para vender o dar seguimiento?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "WhatsApp Business", value: "whatsapp_business" },
						{ label: "CRM", value: "crm" },
						{ label: "Hoja de calculo", value: "spreadsheet" },
						{ label: "Calendario / agenda", value: "calendar" },
						{ label: "Formularios", value: "forms" },
						{ label: "Email marketing", value: "email_marketing" },
						{ label: "Tienda en linea", value: "ecommerce" },
						{ label: "Automatizaciones", value: "automations" },
						{ label: "Ninguna herramienta clara", value: "none" },
						{ label: "No lo se", value: "not_sure" },
					],
				},
			],
		},
		{
			id: "digital_presence",
			title: "Presencia digital",
			subtitle: "Canales",
			description: "Entendemos que tienen hoy, que funciona y que hace falta mejorar.",
			questions: [
				{
					id: "digital_assets",
					type: "multiselect",
					label: "Que activos digitales tienen hoy?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Sitio web", value: "website" },
						{ label: "Landing pages", value: "landing_pages" },
						{ label: "Blog / articulos", value: "blog" },
						{ label: "Tienda en linea", value: "ecommerce" },
						{ label: "Instagram", value: "instagram" },
						{ label: "Facebook", value: "facebook" },
						{ label: "TikTok", value: "tiktok" },
						{ label: "LinkedIn", value: "linkedin" },
						{ label: "YouTube", value: "youtube" },
						{ label: "Lista de correos", value: "email_list" },
						{ label: "CRM", value: "crm" },
						{ label: "Google Business Profile", value: "google_business" },
						{ label: "Ninguno claro", value: "none" },
					],
				},
				{
					id: "digital_what_works",
					type: "textarea",
					label: "Que funciona bien de su presencia digital actual?",
					required: false,
					rows: 4,
				},
				{
					id: "digital_what_fails",
					type: "textarea",
					label: "Que no esta funcionando o les incomoda?",
					required: true,
					rows: 4,
				},
				{
					id: "digital_desired_actions",
					type: "multiselect",
					label: "Que acciones deberia poder realizar una persona facilmente?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Contactar", value: "contact" },
						{ label: "Agendar", value: "schedule" },
						{ label: "Solicitar cotizacion", value: "quote" },
						{ label: "Comprar", value: "buy" },
						{ label: "Pagar", value: "pay" },
						{ label: "Comparar opciones", value: "compare" },
						{ label: "Leer contenido", value: "read" },
						{ label: "Descargar material", value: "download" },
						{ label: "Suscribirse", value: "subscribe" },
						{ label: "Aplicar / registrarse", value: "apply" },
						{ label: "Pedir informacion", value: "request_info" },
						{ label: "No lo tenemos claro", value: "not_sure" },
					],
				},
				{
					id: "digital_measurement_tools",
					type: "multiselect",
					label: "Que herramientas de medicion usan hoy?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Google Analytics", value: "google_analytics" },
						{ label: "Google Search Console", value: "search_console" },
						{ label: "Google Tag Manager", value: "tag_manager" },
						{ label: "Meta Pixel", value: "meta_pixel" },
						{ label: "Reportes de anuncios", value: "ads_dashboard" },
						{ label: "Reportes de CRM", value: "crm_reports" },
						{ label: "Hotjar / Microsoft Clarity / mapas de calor", value: "heatmaps" },
						{ label: "Ninguna", value: "none" },
						{ label: "No lo se", value: "not_sure" },
					],
				},
			],
		},
		{
			id: "project_needs",
			title: "Necesidades del proyecto",
			subtitle: "Que creen que necesitan",
			description:
				"Pueden elegir varias opciones. No pasa nada si todavia no esta claro; aqui buscamos el panorama inicial.",
			questions: [
				{
					id: "project_needs_primary",
					type: "multiselect",
					label: "Que creen que necesitan?",
					description: "Pueden elegir varias. No pasa nada si todavia no esta claro.",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Sitio web / plataforma", value: "website" },
						{ label: "SEO / visibilidad organica", value: "seo" },
						{ label: "Contenido", value: "content" },
						{ label: "Marca / identidad", value: "brand" },
						{ label: "Anuncios / pauta digital", value: "ads" },
						{ label: "CRM / seguimiento comercial", value: "crm" },
						{ label: "Automatizacion / operaciones", value: "automation" },
						{ label: "Medicion / analitica", value: "analytics" },
						{ label: "Venta en linea / pagos", value: "ecommerce" },
						{ label: "Estrategia / roadmap", value: "strategy" },
						{ label: "No lo tengo claro todavia", value: "not_sure" },
					],
				},
			],
		},
		{
			id: "conditional_modules_intro",
			title: "Modulos condicionales",
			subtitle: "Necesidades detectadas",
			description:
				"Segun lo que seleccionaste, ahora vemos preguntas especificas para aterrizar cada necesidad.",
			visibleWhen: {
				questionId: "project_needs_primary",
				operator: "notEmpty",
			},
			questions: [
				{
					id: "conditional_modules_copy",
					type: "static",
					content:
						"<p>A continuacion solo veras los modulos que apliquen a tus necesidades seleccionadas.</p>",
				},
			],
		},
		{
			id: "conditional_modules_website",
			title: "Modulo web",
			subtitle: "Sitio web / plataforma",
			visibleWhen: {
				questionId: "project_needs_primary",
				operator: "includesAny",
				value: ["website"],
			},
			questions: [
				{
					id: "website_goal",
					type: "radio",
					label: "Que objetivo principal debe cumplir el sitio web?",
					required: true,
					options: [
						{ label: "Generar confianza", value: "trust" },
						{ label: "Generar prospectos", value: "leads" },
						{ label: "Vender en linea", value: "sales" },
						{ label: "Explicar mejor la oferta", value: "explain" },
						{ label: "Mostrar trabajo / casos", value: "portfolio" },
						{ label: "Construir autoridad con contenido", value: "authority" },
						{ label: "Facilitar procesos internos o atencion", value: "operations" },
						{ label: "No lo tengo claro", value: "not_sure" },
					],
				},
				{
					id: "website_status",
					type: "radio",
					label: "Que describe mejor el sitio actual?",
					required: true,
					options: [
						{ label: "No tenemos sitio", value: "no_site" },
						{ label: "Existe, pero esta desactualizado", value: "outdated" },
						{ label: "Existe, pero no comunica bien", value: "unclear" },
						{ label: "Existe, pero es lento o tecnico", value: "slow" },
						{ label: "Existe, pero no convierte", value: "no_conversion" },
						{ label: "Funciona aceptablemente", value: "acceptable" },
						{ label: "No lo se", value: "not_sure" },
					],
				},
			],
		},
		{
			id: "conditional_modules_seo",
			title: "Modulo SEO",
			subtitle: "Visibilidad organica",
			visibleWhen: {
				questionId: "project_needs_primary",
				operator: "includesAny",
				value: ["seo"],
			},
			questions: [
				{
					id: "seo_priority_searches",
					type: "textarea",
					label: "Por que temas, productos, servicios o busquedas les gustaria aparecer en Google?",
					required: true,
					rows: 4,
				},
				{
					id: "seo_geography",
					type: "multiselect",
					label: "Que zonas geograficas son prioritarias?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Ciudad o zona local", value: "local_city" },
						{ label: "Estado / region", value: "state" },
						{ label: "Nacional", value: "national" },
						{ label: "Internacional", value: "international" },
						{ label: "No depende de ubicacion", value: "no_geo" },
						{ label: "No lo tenemos claro", value: "not_sure" },
					],
				},
			],
		},
		{
			id: "conditional_modules_content",
			title: "Modulo de contenido",
			subtitle: "Contenido",
			visibleWhen: {
				questionId: "project_needs_primary",
				operator: "includesAny",
				value: ["content"],
			},
			questions: [
				{
					id: "content_types",
					type: "multiselect",
					label: "Que tipo de contenido necesitan producir o ordenar?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Articulos / blog", value: "blog" },
						{ label: "Copys para pagina web", value: "website_copy" },
						{ label: "Landing pages", value: "landing" },
						{ label: "Redes sociales", value: "social" },
						{ label: "Email marketing", value: "email" },
						{ label: "Casos de exito", value: "cases" },
						{ label: "Guiones / videos", value: "video" },
						{ label: "Piezas comerciales", value: "commercial" },
						{ label: "No lo tenemos claro", value: "not_sure" },
					],
				},
				{
					id: "content_priority",
					type: "textarea",
					label: "Que mensaje o tema deberia tener prioridad?",
					required: true,
					rows: 4,
				},
			],
		},
		{
			id: "conditional_modules_brand",
			title: "Modulo de marca",
			subtitle: "Identidad",
			visibleWhen: {
				questionId: "project_needs_primary",
				operator: "includesAny",
				value: ["brand"],
			},
			questions: [
				{
					id: "brand_assets",
					type: "multiselect",
					label: "Que elementos de marca tienen hoy?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Logo", value: "logo" },
						{ label: "Colores", value: "colors" },
						{ label: "Tipografias", value: "typography" },
						{ label: "Manual de marca", value: "brand_manual" },
						{ label: "Mensajes / tono definido", value: "messaging" },
						{ label: "Fotos propias", value: "photos" },
						{ label: "Videos propios", value: "videos" },
						{ label: "Plantillas", value: "templates" },
						{ label: "Nada formal", value: "none" },
						{ label: "No lo se", value: "not_sure" },
					],
				},
				{
					id: "brand_dependency",
					type: "radio",
					label: "La marca debe depender principalmente de una persona, de un equipo o de la institucion?",
					required: true,
					options: [
						{ label: "Persona visible / marca personal", value: "person" },
						{
							label: "Marca con rostro humano de respaldo",
							value: "human_backed_brand",
						},
						{ label: "Equipo", value: "team" },
						{ label: "Institucion / empresa", value: "institution" },
						{ label: "Producto o servicio", value: "product" },
						{ label: "No lo tenemos claro", value: "not_sure" },
					],
				},
			],
		},
		{
			id: "conditional_modules_operations",
			title: "Modulo de operaciones",
			subtitle: "CRM y automatizacion",
			visibleWhen: {
				mode: "any",
				rules: [
					{
						questionId: "project_needs_primary",
						operator: "includesAny",
						value: ["crm", "automation"],
					},
				],
			},
			questions: [
				{
					id: "operations_repetitive_tasks",
					type: "textarea",
					label: "Que tareas se repiten con frecuencia y consumen tiempo?",
					required: true,
					rows: 4,
				},
				{
					id: "operations_tracking_problem",
					type: "multiselect",
					label: "Donde se pierde informacion, seguimiento o visibilidad?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Prospectos", value: "leads" },
						{ label: "Seguimiento", value: "follow_up" },
						{ label: "Cotizaciones / propuestas", value: "quotes" },
						{ label: "Estado de ventas", value: "sales_status" },
						{ label: "Informacion de clientes", value: "customer_info" },
						{ label: "Tareas internas", value: "tasks" },
						{ label: "Reportes", value: "reporting" },
						{ label: "Entregas entre personas o areas", value: "handoff" },
						{ label: "No lo sabemos", value: "not_sure" },
					],
				},
			],
		},
		{
			id: "conditional_modules_analytics",
			title: "Modulo de analitica",
			subtitle: "Medicion",
			visibleWhen: {
				questionId: "project_needs_primary",
				operator: "includesAny",
				value: ["analytics"],
			},
			questions: [
				{
					id: "analytics_key_metrics",
					type: "multiselect",
					label: "Que metricas necesitan seguir con mas claridad?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Visitas", value: "traffic" },
						{ label: "Leads", value: "leads" },
						{ label: "Conversion", value: "conversion" },
						{ label: "Ventas", value: "sales" },
						{ label: "Retencion", value: "retention" },
						{ label: "Costo de adquisicion", value: "cac" },
						{ label: "Valor por cliente", value: "lifetime_value" },
						{ label: "No lo tenemos claro", value: "not_sure" },
					],
				},
				{
					id: "analytics_current_reporting",
					type: "radio",
					label: "Como describirias su medicion actual?",
					required: true,
					options: [
						{ label: "No medimos casi nada", value: "none" },
						{ label: "Medimos parcialmente", value: "partial" },
						{ label: "Medimos bien", value: "good" },
						{ label: "No lo se", value: "not_sure" },
					],
				},
			],
		},
		{
			id: "conditional_modules_ads",
			title: "Modulo de anuncios",
			subtitle: "Pauta digital",
			visibleWhen: {
				questionId: "project_needs_primary",
				operator: "includesAny",
				value: ["ads"],
			},
			questions: [
				{
					id: "ads_ad_experience",
					type: "radio",
					label: "Han invertido antes en anuncios?",
					required: true,
					options: [
						{ label: "No", value: "never" },
						{ label: "Si, pero sin buenos resultados", value: "tried_no_results" },
						{ label: "Si, actualmente invertimos", value: "active" },
						{ label: "Si, y funciono antes", value: "past_success" },
						{ label: "No lo se", value: "not_sure" },
					],
				},
			],
		},
		{
			id: "conditional_modules_ecommerce",
			title: "Modulo ecommerce",
			subtitle: "Pagos y venta en linea",
			visibleWhen: {
				questionId: "project_needs_primary",
				operator: "includesAny",
				value: ["ecommerce"],
			},
			questions: [
				{
					id: "ecommerce_transaction_type",
					type: "multiselect",
					label: "Que tipo de transaccion necesitan facilitar?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Compra de productos", value: "product_purchase" },
						{ label: "Pago de servicios", value: "service_payment" },
						{ label: "Anticipo / apartado", value: "deposit" },
						{ label: "Suscripcion", value: "subscription" },
						{ label: "Cotizacion a pago", value: "quote_to_pay" },
						{ label: "Reserva con pago", value: "booking_payment" },
						{ label: "No lo tenemos claro", value: "not_sure" },
					],
				},
			],
		},
		{
			id: "conditional_modules_strategy",
			title: "Modulo de estrategia",
			subtitle: "Roadmap",
			visibleWhen: {
				questionId: "project_needs_primary",
				operator: "includesAny",
				value: ["strategy"],
			},
			questions: [
				{
					id: "strategy_focus",
					type: "multiselect",
					label: "Que deberia resolver primero la estrategia?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Prioridad y orden de trabajo", value: "priority" },
						{ label: "Alcance y fases", value: "phases" },
						{ label: "Posicionamiento", value: "positioning" },
						{ label: "Conversion", value: "conversion" },
						{ label: "Contenido", value: "content" },
						{ label: "Lanzamiento", value: "launch" },
						{ label: "No lo tenemos claro", value: "not_sure" },
					],
				},
				{
					id: "strategy_short_term_goal",
					type: "textarea",
					label: "Que seria una victoria rapida en los proximos 30 a 90 dias?",
					required: true,
					rows: 4,
				},
			],
		},
		{
			id: "conditional_modules_clarity",
			title: "Modulo de claridad",
			subtitle: "Cuando aun no esta definido",
			visibleWhen: {
				questionId: "project_needs_primary",
				operator: "includesAny",
				value: ["not_sure"],
			},
			questions: [
				{
					id: "clarity_biggest_uncertainty",
					type: "multiselect",
					label: "Que es lo que menos tienen claro en este momento?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "El problema real", value: "problem" },
						{ label: "Que solucion necesitamos", value: "solution" },
						{ label: "Por donde empezar", value: "priority" },
						{ label: "Cuanto invertir", value: "budget" },
						{ label: "Cuando hacerlo", value: "timing" },
						{ label: "A quien enfocarnos", value: "audience" },
						{ label: "Que oferta impulsar", value: "offer" },
						{ label: "Que canales usar", value: "channels" },
					],
				},
			],
		},
		{
			id: "brand_references",
			title: "Marca, tono y referencias",
			subtitle: "Identidad",
			description:
				"Definimos tono, referencias positivas, lo que no quieren y material de apoyo.",
			questions: [
				{
					id: "brand_tone",
					type: "multiselect",
					label: "Que tono debe transmitir la marca?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Profesional", value: "professional" },
						{ label: "Cercano", value: "close" },
						{ label: "Educativo", value: "educational" },
						{ label: "Tecnico", value: "technical" },
						{ label: "Premium", value: "premium" },
						{ label: "Institucional", value: "institutional" },
						{ label: "Calido", value: "warm" },
						{ label: "Atrevido", value: "bold" },
						{ label: "Sobrio / calmado", value: "calm" },
						{ label: "Divertido", value: "playful" },
						{ label: "No lo tenemos claro", value: "not_sure" },
					],
				},
				{
					id: "brand_liked_references",
					type: "textarea",
					label: "Que marcas, sitios o experiencias les gustan como referencia y por que?",
					required: false,
					rows: 4,
				},
				{
					id: "brand_disliked_references",
					type: "textarea",
					label: "Que estilos, mensajes o enfoques quieren evitar?",
					required: false,
					rows: 4,
				},
				{
					id: "brand_files",
					type: "file",
					label: "Pueden compartir materiales utiles?",
					description:
						"Logo, manual de marca, fotos, videos, presentaciones, casos, catalogos, reportes o documentos.",
					required: false,
					multiple: true,
					maxFiles: 10,
					maxSizeMb: 25,
					accept: [".pdf", ".ai", ".fig", ".psd", ".docx", ".pptx", ".xlsx", "image/*"],
				},
			],
		},
		{
			id: "scope_decision",
			title: "Alcance, presupuesto, tiempos y decision",
			subtitle: "Decision",
			description:
				"Aterrizamos urgencia, presupuesto, quien decide y que esperan ver en una propuesta.",
			questions: [
				{
					id: "scope_urgency",
					type: "radio",
					label: "Que tan urgente es iniciar?",
					required: true,
					options: [
						{ label: "Inmediato", value: "immediate" },
						{ label: "Este mes", value: "this_month" },
						{ label: "En 1 a 3 meses", value: "next_1_3_months" },
						{ label: "Mas adelante", value: "later" },
						{ label: "Solo estamos explorando", value: "exploratory" },
					],
				},
				{
					id: "scope_target_date",
					type: "date",
					label: "Hay una fecha ideal o limite para tener una primera version?",
					required: false,
				},
				{
					id: "scope_budget_range",
					type: "radio",
					label: "Tienen un rango de inversion previsto?",
					required: false,
					options: [
						{ label: "Menos de $25,000 MXN", value: "under_25k" },
						{ label: "$25,000 - $50,000 MXN", value: "25k_50k" },
						{ label: "$50,000 - $100,000 MXN", value: "50k_100k" },
						{ label: "$100,000 - $250,000 MXN", value: "100k_250k" },
						{ label: "Mas de $250,000 MXN", value: "250k_plus" },
						{ label: "No esta definido", value: "not_defined" },
						{ label: "Prefiero conversarlo", value: "prefer_discuss" },
					],
				},
				{
					id: "scope_decision_makers",
					type: "multiselect",
					label: "Quien participa en la decision final?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Yo", value: "respondent" },
						{ label: "Socio / socios", value: "partner" },
						{ label: "Direccion", value: "director" },
						{ label: "Marketing", value: "marketing" },
						{ label: "Ventas", value: "sales" },
						{ label: "Operaciones", value: "operations" },
						{ label: "Finanzas", value: "finance" },
						{ label: "Legal / compliance", value: "legal" },
						{ label: "Asesor externo", value: "external" },
						{ label: "No lo se todavia", value: "not_sure" },
					],
				},
				{
					id: "scope_proposal_needs",
					type: "multiselect",
					label: "Que necesitan ver para tomar una decision con confianza?",
					required: true,
					maxSelections: 5,
					options: [
						{ label: "Diagnostico claro", value: "diagnosis" },
						{ label: "Alcance detallado", value: "scope" },
						{ label: "Fases / roadmap", value: "phases" },
						{ label: "Tiempos", value: "timeline" },
						{ label: "Inversion", value: "investment" },
						{ label: "Entregables", value: "deliverables" },
						{ label: "Ejemplos o referencias", value: "examples" },
						{ label: "Metricas de exito", value: "metrics" },
						{ label: "Proceso de trabajo", value: "process" },
						{ label: "Responsabilidades de cada parte", value: "responsibilities" },
					],
				},
			],
		},
		{
			id: "closing",
			title: "Cierre y confirmacion",
			subtitle: "Ultimo paso",
			description: "Solo faltan un par de cierres para dejar listo el envio final.",
			questions: [
				{
					id: "closing_one_sentence_need",
					type: "textarea",
					label: "Si tuvieran que resumir lo que necesitan en una sola frase, cual seria?",
					required: true,
					rows: 4,
				},
				{
					id: "closing_missing_context",
					type: "textarea",
					label: "Que informacion importante no preguntamos y deberiamos saber?",
					required: false,
					rows: 4,
				},
				{
					id: "closing_confirmation",
					type: "radio",
					label: "Confirmas que podemos usar esta informacion para preparar el brief y el siguiente paso comercial?",
					required: true,
					options: [
						{ label: "Si, confirmado", value: "yes" },
						{ label: "No por ahora", value: "no" },
					],
				},
			],
		},
	],
}
